### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by TimurHadzic** [Logofet/GO-project#2]
Hello, I will write you a review for the code, some things can be improved here :D :

1.) The main function contains an infinite loop with an HTTP server inside. This is not recommended since the program will be stuck in a infinite loop. It's also better to move the HTTP server code to a separate function and call that from the main function.

2.) You should structure your code into sections, for example all the handlers should be created as separate functions and could be moved to a package called for example "Server", all the database queries could also be separated into functions, and moved to another package, for example "Database". That makes your code much more cleaner to read and to edit if you need to add aditional features.

3.) The code does not handle errors returned by the json.NewDecoder(r.Body).Decode(&user) function. If there is an error decoding the request body, a better approach would be to return a 400 Bad Request response and include a meaningful error message that includes where the handler failed (name of the function that was called). Also i noticed that alot of your error handling does not contain much information, it could contain the line of the code that failed, the function name that failed etc.

4.) The program is hardcoded to use a specific MySQL database, username, and password. It would be better to load a config file that contains all the information or use environment variables to configure these values, making the code more flexible and secure.

**Comment by KenanHH** [comment]
Thanks Timur for a review. @Logofet please work around these issues that Timur mentioned, and we will do a review again.

**Comment by Logofet** [comment]
Thank you for the review, all of the issues mentioned above have been resolved.
